ID-B-3-add-volunteer
SlavaV679/FindYourFriendAmongPets pull request #4
Opened 2024-08-12 15:05 UTC by SlavaV679

add volunteer

2024-08-12 15:18 UTC, YADARAN1 requested changes

2024-08-12 15:18 UTC, YADARAN1 commented on backend/FindYourFriendAmongPets/FindYourFriendAmongPets.Core/Models/Volunteer.cs
> +    public string FullName { get; private set; }
Сделай из FullName ValueObject

2024-08-13 12:44 UTC, SlavaV679 commented on backend/FindYourFriendAmongPets/FindYourFriendAmongPets.Core/Models/Volunteer.cs
> +    public string FullName { get; private set; }
исправлено в комите [ID-B-3-add-FullName-as-Value-Object](https://github.com/SlavaV679/FindYourFriendAmongPets/pull/4/commits/58c1d406c025fc1d5aaf2fe1caa20fd23f530881)

2024-08-13 13:07 UTC, YADARAN1 approved these changes

2024-08-13 13:07 UTC, YADARAN1 commented on backend/FindYourFriendAmongPets/FindYourFriendAmongPets.Core/Models/FullName.cs
> +
Стоит добавить ещё и отчество, но оно может быть null

2024-08-13 14:11 UTC, SlavaV679 commented on backend/FindYourFriendAmongPets/FindYourFriendAmongPets.Core/Models/FullName.cs
> +
добавил

2024-08-13 14:11 UTC, merged